Repository vivekuppal/transcribe, pull requests merged in 2023-09, with the labels that each got.

#55 Multiturn prompts, bug fixes
  AudioTranscriber.py
  GPTResponder.py
  GlobalVars.py
  audio_player.py
  constants.py
  conversation.py
  main.py
  multiturn.py
  parameters.yaml
  prompts.py
  ui.py
Labels: bug, enhancement

#56 Allow enable/disable speaker and microphone from UI
  GlobalVars.py
  main.py
  ui.py
Labels: enhancement

#60 Readme Update
  README.md
  parameters.yaml
Labels: documentation

#64 Continuous mode broke after updates to the UI.
  ui.py
Labels: bug

#65 Clear transcript data from UI
  AudioTranscriber.py
  conversation.py
  duration.py
Labels: bug

#67 Make a single transcription duration configurable
  AudioRecorder.py
  parameters.yaml
  ui.py
Labels: Code Design Requirement
