Repository vivekuppal/transcribe, pull requests merged in 2023-07, with the labels that each got.

#18 Add support for multiple languages
  TranscriberModels.py
  language.py
  main.py
  ui.py
Labels: enhancement

#20 Easy install for non developers on windows
  .gitignore
  AudioRecorder.py
  AudioTranscriber.py
  README.md
  custom_speech_recognition/__init__.py
  generate_binary.bat
  globals.py
  interactions.py
  language.py
  main.py
  requirements.txt
  ui.py
Labels: enhancement

#26 Language combo fix
  language.py
Labels: enhancement

#27 Added gdrive
  README.md
  TranscriberModels.py
Labels: documentation, enhancement

#28 Allow usage of API Key in installed version of Transcribe
  GPTResponder.py
  GlobalVars.py
  README.md
  Singleton.py
  configuration.py
  generate_binary.bat
  keys.py
  main.py
  parameters.yaml
  requirements.txt
  ui.py
Labels: enhancement

#34 --api option was not working correctly
  TranscriberModels.py
  main.py
  ui.py
Labels: bug

#36 Create unit tests for speech recognition
  README.md
  requirements.txt
  tests/__init__.py
  tests/audio-mono-16-bit-44100Hz.aiff
  tests/audio-mono-16-bit-44100Hz.flac
  tests/audio-mono-24-bit-44100Hz.flac
  tests/audio-stereo-16-bit-44100Hz.aiff
  tests/audio-stereo-16-bit-44100Hz.flac
  tests/audio-stereo-24-bit-44100Hz.flac
  tests/chinese.flac
  tests/french.aiff
  tests/test_audio.py
  tests/test_recognition.py
Labels: Test

#42 Logging Infrastructure
  .gitignore
  AudioRecorder.py
  AudioTranscriber.py
  GPTResponder.py
  GlobalVars.py
  app_logging.py
  constants.py
  interactions.py
  main.py
  parameters.yaml
  ui.py
Labels: Code Design Requirement

#44 Get Response from LLM on demand
  GPTResponder.py
  GlobalVars.py
  constants.py
  main.py
  ui.py
Labels: enhancement
